In [1]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
accelerate                       0.32.1
aiohttp                          3.9.5
aiosignal                        1.3.1
alabaster                        0.7.16
albucore                         0.0.12
albumentations                   1.4.11
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.18.0
asn1crypto                       1.5.1
astropy                          6.1.2
astropy-iers-data                0.2024.7.22.0.34.13
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            23.2.0
audioread                        3.0.1
autograd                

In [6]:
import tensorflow as tf
!pip install ipykernel

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 32.9 MB/s eta 0:00:00


In [18]:
# Numpy tutorial

import numpy as np

# 1 dimensional
x = np.array(12)

print(x.shape)

print(type(x))


# 2D array : stack of multiple 1-D array
x = np.array([[1,2,3], [4,5,6]])
print(x, x.shape)


# 3D arrray
x = np.array([[[1,2,4]]])

print(x, x.shape)

# example

x = np.array([[1,2],[3,4], [5,6], [7,8]])

print(x, x.shape)

()
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]] (2, 3)
[[[1 2 4]]] (1, 1, 3)
[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)


Tensorflow convention : data is always presented in matrices form.

In [2]:
# Neural network implementation in Python, without using Tensorflow
# Hard coding example

import numpy as np

x = np.array([200.0, 17.0])

# compute activation values of layer1 , units = 2
w1_1 = np.array([1, 2])
b1_1 = np.array([-1])
z1_1 = np.dot(w1_1, x) + b1_1
a1_1 = sigmoid(z1_1)

w1_2 = np.array([-3, 4])
b1_2 = np.array([1])
z1_2 = np.dot(w1_2, x) + b1_2
a2_1 = sigmoid(z1_2)

w1_3 = np.array([-4, 5])
b1_3 = np.array([-2])
z1_3 = np.dot(w1_3, x) + b1_3
a3_1 = sigmoid(z1_3)


a1 = np.array([a1_1, a2_1, a3_1])

# 2nd layer
w2_1 = np.array([-7, 8, 9])
b2_1 = np.array([3])
z2_1 = np.dot(w2_1, a1) + b2_1



# general Neural network , no hard coding
# General implementation of forward propagation
# write a function to implement a dense function
def dense(a_in, W, b):
  units = W.shape[1]
  a_out = np.zeros(units)
  for j in range(units):
    w= W[:, j]              # pulling out the w values as a column
    z= np.dot(w, a_in) + b[j]   # calculating the z value
    a_out = g(z)
  return a_out

def sequential(x):
  a1 = dense(x, W1, b1)
  a2 = dense(a1, W2, b2)
  a3 = dense(a2, W3, b3)
  a4 = dense(a3, W4, b4)
  f_x = a4
  return f_x

NameError: name 'sigmoid' is not defined